### ISSUE TITLE
Add a privacy policy

### ISSUE THREAD

**Issue by trinkey** [jerimiah-smiggins/smiggins#100]
just like have it show what is collected and stored, like
* we only collect information you give and submit
* your password is never stored in plain text
* we only store your settings, posts, comments, and likes, no telemetry or any fingerprinting data about you

and maybe also put stuff like
* we have the right to use anything you put on this platform for commercial gain
* we are not responsible if your passwords get stolen if you accidentally post them

or other stuff too idk i can read some privacy policies later for more inspiration

**Comment by Subroutine7901** [comment]
"we are not responsible if your passwords get stolen if you accidentally post them"
*owner proceeds to steal passwords and not be responsible*

**Comment by Subroutine7901** [comment]
Also the privacy policy should be in the settings, as it would depend on the instance's owner.

**Comment by trinkey** [comment]
true, this should be easily editable, maybe in like a text file next to settings.py that just gets templated or something

also technicalllyyyy im stealing tokens not direct passwords

**Comment by Subroutine7901** [comment]
@trinkey Start working on a draft for it and I might get to adding it backend once that's done, then you can add it frontend

**Comment by trinkey** [comment]
remind me over the weekend

**Comment by trinkey** [comment]
have fun 3d printing your 3d printer i can try to remember but no promises

**Comment by Subroutine7901** [comment]
Mi volas morti

**Comment by trinkey** [comment]
<details>
<summary>how does this look</summary>
# Privacy Policy
Last updated: April 05, 2024

This Privacy Policy describes Our policies and procedures on the collection, use
and disclosure of Your information when You use the Service and tells You about
Your privacy rights and how the law protects You.

We use Your Personal data to provide and improve the Service. By using the
Service, You agree to the collection and use of information in accordance with
this Privacy Policy.

## Interpretation and Definitions
### Interpretation
The words of which the initial letter is capitalized have meanings defined under
the following conditions. The following definitions shall have the same meaning
regardless of whether they appear in singular or in plural.

### Definitions
For the purposes of this Privacy Policy:
- __Account__ means a unique account created for You to access our Service or
  parts of our Service.
- __Affiliate__ means an entity that controls, is controlled by or is under
  common control with a party, where "control" means ownership of 50% or more of
  the shares, equity interest or other securities entitled to vote for election
  of directors or other managing authority.
- __Company__ (referred to as either "the Company", "We", "Us" or "Our" in this
  Agreement) refers to Smiggins.
- __Cookies__ are small files that are placed on Your computer, mobile device or
  any other device by a website, containing the details of Your browsing history
  on that website among its many uses.
- __Country__ refers to: United States
- __Device__ means any device that can access the Service such as a computer, a
  cellphone or a digital tablet.
- __Personal Data__ is any information that relates to an identified or
  identifiable individual.
- __Service__ refers to the Website.
- __Service Provider__ means any natural or legal person who processes the data
  on behalf of the Company. It refers to third-party companies or individuals
  employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.
- __Usage Data__ refers to data collected automatically, either generated by the
  use of the Service or from the Service infrastructure itself (for example, the
  duration of a page visit).
- __Website__ refers to Smiggins, accessible from https://trinkey.pythonanywhere.com
- __You__ means the individual accessing or using the Service, or the company,
  or other legal entity on behalf of which such individual is accessing or using
  the Service, as applicable.

## Collecting and Using Your Personal Data
### Types of Data Collected
#### Personal Data
While using Our Service, We will never ask you to provide any personally
identifiable information. We will never ask for an email address, phone number,
name, or anything else.

#### Usage Data
Usage Data is not actively collected, however may be temporairly stored in the
server logs. Information there can contain the following:
- IP Addresses
- User Agent
- Request status and URLs
- Timestamps of requests

This information will not be traced back to your account in any way at any time.
We do not use this information in any way other than to help fix issues in the
Service.

#### Tracking Technologies and Cookies
We do not use Cookies or other similar similar technologies to track You in any
way. The only way that we would use these technologies is to:
- Tell the server that You are logged in and to what account
- Store and apply any client-side settings You select

### Use of Your Personal Data
The Company may use Personal Data for the following purposes:
- __To manage Your Account__: to manage Your registration as a user of the
  Service. The Personal Data You provide can give You access to different
  functionalities of the Service that are available to You as a registered user.
- __For other purposes__: We may use Your information for other purposes, for
  example creating public statistics, seeing what features are being used, and
  possibly more.

We may share Your personal information in the following situations:
- __With storage providers__: Your personal information will be stored on
  PythonAnywhere's third party servers. They will technically have access to it.
- __With other users__: when You share personal information or otherwise
  interact in the public areas with other users, such information may be viewed
  by all users and may be publicly distributed outside. 
- __With Your consent__: We may disclose Your personal information for any other
  purpose with Your consent.

### Retention of Your Personal Data
The Company will retain Your Personal Data only for as long as is necessary for
the purposes set out in this Privacy Policy. We will retain and use Your
Personal Data to the extent necessary to comply with our legal obligations (for
example, if we are required to retain your data to comply with applicable laws),
resolve disputes, and enforce our legal agreements and policies. The Company
will also retain Usage Data for internal analysis purposes. Usage Data is
generally retained for a shorter period of time, except when this data is used
to strengthen the security or to improve the functionality of Our Service, or We
are legally obligated to retain this data for longer time periods.

### Transfer of Your Personal Data
Your information, including Personal Data, is processed at the Company's
operating offices and in any other places where the parties involved in the
processing are located. It means that this information may be transferred to —
and maintained on — computers located outside of Your state, province, country
or other governmental jurisdiction where the data protection laws may differ
than those from Your jurisdiction. Your consent to this Privacy Policy followed
by Your submission of such information represents Your agreement to that
transfer. The Company will take all steps reasonably necessary to ensure that
Your data is treated securely and in accordance with this Privacy Policy and no
transfer of Your Personal Data will take place to an organization or a country
unless there are adequate controls in place including the security of Your data
and other personal information.

### Delete Your Personal Data
You have the right to delete or request that We assist in deleting the Personal
Data that We have collected about You. Our Service may give You the ability to
delete certain information about You from within the Service. You may update,
amend, or delete Your information at any time by signing in to Your Account, if
you have one, and visiting the settings section which allows you to manage Your
personal information. You may also contact Us to request access to, correct, or
delete any personal information that You have provided to Us. Please note,
however, that We may need to retain certain information when we have a legal
obligation or lawful basis to do so.

### Disclosure of Your Personal Data
#### Business Transactions
We will never consider being bought or inherited by another company, so any of
the data We have on You will not be knowingly given to another company in
response to an acquisition.

#### Law enforcement
Under certain circumstances, the Company may be required to disclose Your
Personal Data if required to do so by law or in response to valid requests by
public authorities (e.g. a court or a government agency).

#### Other legal requirements
The Company may disclose Your Personal Data in the good faith belief that such
action is necessary to:
- Comply with a legal obligation
- Protect and defend the rights or property of the Company
- Prevent or investigate possible wrongdoing in connection with the Service
- Protect the personal safety of Users of the Service or the public
- Protect against legal liability

### Security of Your Personal Data
The security of Your Personal Data is important to Us, but remember that no
method of transmission over the Internet, or method of electronic storage is
100% secure. While We strive to use commercially acceptable means to protect
Your Personal Data, We cannot guarantee its absolute security.

## Children's Privacy
Our Service does not address anyone under the age of 13. We do not knowingly
collect personally identifiable information from anyone under the age of 13. If
You are a parent or guardian and You are aware that Your child has provided Us
with Personal Data, please contact Us. If We become aware that We have collected
Personal Data from anyone under the age of 13 without verification of parental
consent, We will take steps to remove that information from Our servers. If We
need to rely on consent as a legal basis for processing Your information and
Your country requires consent from a parent, We may require Your parent's
consent before We collect and use that information.

## Links to Other Websites
Our Service may contain links to other websites that are not operated by Us. If
You click on a third party link, You will be directed to that third party's
site. We have no control over and assume no responsibility for the content,
privacy policies or practices of any third party sites or services.

## Changes to this Privacy Policy
We may update Our Privacy Policy from time to time. You may be prompted to
review the new Privacy Policy when it is changed, however you will never be
directly contacted about it. You are advised to review this Privacy Policy
periodically for any changes. Changes to this Privacy Policy are effective when
they are posted on this page.

## Contact Us
If you have any questions about this Privacy Policy, You can contact us:
- By email: trinkey@duck.com
- By visiting this page: https://trinkey.pythonanywhere.com/contact
</details>

**Comment by catsarenice1** [comment]
Make sure to state that their account isn't their property and can be moderated, deleted or reassigned at any moment.

**Comment by trinkey** [comment]
> I personally worry about commitments saying that you'll never ask for an email, phone number etc... or ever get aquired.

email i should remove but not phone because fees but the acquired one is literally never going to happen even if i do get a good offer i would refuse

**Comment by trinkey** [comment]
yknow we could just like *not* do this

**Comment by trinkey** [comment]
because it is like instanced there would be some weird implications with having some default stuff, not to mention enforcing anything across any instance that's not main isn't possible and is up to the instance owner

**Comment by trinkey** [comment]
because it is like instanced there would be some weird implications with having some default stuff, not to mention enforcing anything across any instance that's not main isn't possible and is up to the instance owner

**Comment by trinkey** [comment]
this isn't like something i think we should have especially since this website is hostable by anyone so i'm gonna close as not planned for now
