### ISSUE TITLE
use the banner color as a pseudo-pfp

### ISSUE THREAD

**Issue by trinkey** [jerimiah-smiggins/smiggins#116]
possible concept:

![image](https://github.com/trinkey/social-media-thing/assets/97406176/ffe09ee5-d4a7-4b0d-b19d-e609ffe1b1b3)

**Comment by trinkey** [comment]
@Subroutine7901 what do you think

**Comment by Subroutine7901** [comment]
Nah, just let them add pfps. I get that it requires moderation so maybe require approval as a setting. But that would be annoying. Maybe add a pfp_approved to a user and it sets to false if they try to change it? Oh but then it requires hosting files hmm idk

**Comment by Subroutine7901** [comment]
But I think the pseudo pfp idea doesn't really look good, at least with the shadow and username overlap

**Comment by trinkey** [comment]
> But I think the pseudo pfp idea doesn't really look good, at least with the shadow and username overlap

itll definitely need lots of tweaking

**Comment by trinkey** [comment]
the only reason i think this is a good idea is because currently there isn't really any real variation between users' posts. another way we could do this is to have the user's color choice be global instead of localStorage and have the color of a post depend on that, although that should have a setting to disable if we do that

**Comment by Subroutine7901** [comment]
I think the color choice shouldn't affect how other users see your posts, but maybe adding the color as a display name color instead of a circle would look good, just make sure it has shadow or something

**Comment by trinkey** [comment]
color as in like the one you set in settings not the banner color

**Comment by trinkey** [comment]
but also i feel like it could get cluttered

**Comment by trinkey** [comment]
maybe instead of there being a circle the like icon could have that as the fill color? and i guess comment too? or maybe we could just go all out and add more icons (for #104) and color those instead?

**Comment by DiamondTaco** [comment]
what about those default pfp generator things, you could try to customize the color

**Comment by trinkey** [comment]
that's lame also the images would have to be generated programmatically every time they're needed to prevent file usage aka hell
