### ISSUE TITLE
even MORE backend options

### ISSUE THREAD

**Issue by trinkey** [jerimiah-smiggins/smiggins#188]
- disable changelog
- disable contact page
- disable polls (when #187 gets merged)
- disable pins
- disable account switcher
- disable signing up completely (will need to be indicated on the index page and signup page when not logged in)
- disable viewing content when logged out

**Comment by Subroutine7901** [comment]
Disable viewing posts, accounts, etc., when not logged in?

**Comment by trinkey** [comment]
good idea shouldnt be too hard either

**Comment by Subroutine7901** [comment]
> good idea shouldnt be too hard either

call the option "fix a bunch of bugs at 'no' expense"

**Comment by Subroutine7901** [comment]
yeah lol
