### ISSUE TITLE
client freaks out if you switch to a deleted account

### ISSUE THREAD

**Issue by trinkey** [jerimiah-smiggins/smiggins#195]

**Comment by Subroutine7901** [comment]
Maybe add checks upon switching to an account to check if it exists, and if not remove it from the account switcher

**Comment by trinkey** [comment]
> Maybe add checks upon switching to an account to check if it exists

well yes but i dont want to add an api route that just validates an id because security

**Comment by Subroutine7901** [comment]
I mean it redirecting you to the login screen does something to tell so idk
