### ISSUE TITLE
Broken "disable custom checkboxes" custom checkbox when toggled

### ISSUE THREAD

**Issue by Subroutine7901** [jerimiah-smiggins/smiggins#247]
When you toggle on and off "disable custom checkboxes", all checkboxes are custom (as expected) but the checkbox being toggled doesn't change, and stays as if custom boxes were disabled.

**Comment by trinkey** [comment]
this is intentional as if the checkboxes were broken and unable to be toggled for some reason, the user could still disable the custom checkboxes
