### ISSUE TITLE
one time invite codes for signups

### ISSUE THREAD

**Issue by 4kh00** [jerimiah-smiggins/smiggins#262]
Okay, so let's say, hypothetically, that I make a cat club on smiggins (the best cat club platform) but goofy dog club members find the link to my cat club site and start mass-enrolling accounts. Is there a way to set a password before a user could create an account, to keep it members-only?

**Comment by trinkey** [comment]
currently there's a way to disable all signups in settings, however I've been meaning an issue for creating an option to require one-time signup codes to make an account
