### ISSUE TITLE
Add multiple choice polls

### ISSUE THREAD

**Issue by Subroutine7901** [jerimiah-smiggins/smiggins#269]
Shouldn't be too hard :3

**Comment by Subroutine7901** [comment]
Like you can select multiple options, a & b

**Comment by trinkey** [comment]
ah. well this wouldn't be *difficult*, however making this make sense in the frontend would be a massive pain.

**Comment by Subroutine7901** [comment]
:3

**Comment by trinkey** [comment]
i'm gonna say no for now, i might come back to this in the future if i want to
