### ISSUE TITLE
Script to do basic install stuff

### ISSUE THREAD

**Issue by Subroutine7901** [jerimiah-smiggins/smiggins#293]
When installing Smiggins, there are a few things you need to do manually, like make _api_keys.py (or .env with #292), migrate the db, choose a place to collect the static files and collect them, along with anything else I forgot. This would streamline the install process, although not do things like install/configure a proper HTTP server or create superuser accounts.

**Comment by trinkey** [comment]
stuff it would do:
- create _api_keys (or the equivilant)
- run python3 manage.py migrate
- maybe change one setting idk

other than that idk those are all easy to do when setting up

**Comment by trinkey** [comment]
idk i don't personally see this to be super useful, maybe in the future when it would do more than like 3 things?
